apiVersion: v1
kind: Secret
metadata:
  name: app-1-system-24ayaz-secret
  namespace: argocd
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJzZWV0aGluZ3gtZG9ja2VyLnBrZy5jb2RpbmcubmV0L3NlZXRoaW5neC1yZWdpc3RyeS9kb2NrZXIiOnsidXNlcm5hbWUiOiJkb2NrZXItMTY4NDUxODQyMTMzOSIsInBhc3N3b3JkIjoiZGY2ZWE5YTNhMzRlOGY1YTZjOTk1OTg3ODBkZGRkYzJhYzMzMDAwMyIsImF1dGgiOiJaRzlqYTJWeUxURTJPRFExTVRnME1qRXpNems2WkdZMlpXRTVZVE5oTXpSbE9HWTFZVFpqT1RrMU9UZzNPREJrWkdSa1l6SmhZek16TURBd013PT0ifX19
